export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const FETCH_ROBOTS_REQUEST = "FETCH_ROBOTS_REQUEST";
export const FETCH_ROBOTS_SUCCESS = "FETCH_ROBOTS_SUCCESS";
export const FETCH_ROBOTS_FAILURE = "FETCH_ROBOTS_FAILURE";
